In [1]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  73  66  61  93  67
7   謝欣蓉  女  70  95  69  99  69
8   羅淑芬  女  90  67  55  53  58
9   許美慧  女  86  51  43  93  72
10  廖志豪  男  64  49  97  51  64

In [2]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
13  蘇雅婷  女  42  95  40  86  61
25  洪怡君  女  51  62  99  87  66
30  楊靜宜  女  47  46  93  51  82
39  彭美慧  女  45  95  54  48  62
43  吳雅萍  女  57  40  79  87  51

In [3]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別   國文  英文   數學  地理  歷史   總分    平均    排名
5   王文傑  男   81  63   98  89  89  420  84.0   1.0
45  莊柏融  男   74  96   98  69  66  403  80.6   2.0
14  高浩宇  男   90  87   95  47  84  403  80.6   2.0
7   謝欣蓉  女   70  95   69  99  69  402  80.4   4.0
27  江雅琪  女   69  84   89  91  59  392  78.4   5.0
32  蕭怡伶  女  100  94   72  80  46  392  78.4   5.0
18  王冠廷  男  100  62   91  43  85  381  76.2   7.0
15  王婉茹  女   79  51   91  66  90  377  75.4   8.0
31  曾靜儀  女   60  95   80  82  59  376  75.2   9.0
33  洪裕豪  男   83  93   85  65  48  374  74.8  10.0
20  莊子謙  男   86  48  100  64  74  372  74.4  11.0
24  呂佳瑩  女   86  60   93  54  75  368  73.6  12.0
25  洪怡君  女   51  62   99  87  66  365  73.0  13.0
47  周美玲  女   89  40   95  66  74  364  72.8  14.0
19  呂婉慧  女   83  79   46  62  92  362  72.4  15.0
6   朱冠霖  男   73  66   61  93  67  360  72.0  16.0
41  許淑芬  女   93  59   98  58  44  352  70.4  17.0
37  呂怡靜  女   68  48   71  90  71  348  69.6  18.0
49  曾明哲  男   95  77   74  60  41  347  69.4  19.0
9   許美慧  女   86  51   43  93  72  345  69.0  20.0
12  呂承恩  男   93  88   42  52  69  344  68.8  21.0
28  郭怡萱  女   82  60   67  72  62  343  68.6  22.0
38  邱宗翰  男   83  99   55  44  61  342  68.4  23.0
2   曾彥廷  男   82  43   51  70  96  342  68.4  23.0
36  蕭浩宇  男   99  46   46  94  52  337  67.4  25.0
1   劉彥宏  男   98  87   50  40  58  333  66.6  26.0
44  施子軒  男   68  57   54  98  55  332  66.4  27.0
17  黃裕傑  男   45  94   89  46  57  331  66.2  28.0
29  簡婉慧  女   78  67   75  65  41  326  65.2  29.0
16  莊承翰  男   84  78   44  69  51  326  65.2  29.0
10  廖志豪  男   64  49   97  51  64  325  65.0  31.0
13  蘇雅婷  女   42  95   40  86  61  324  64.8  32.0
8   羅淑芬  女   90  67   55  53  58  323  64.6  33.0
30  楊靜宜  女   47  46   93  51  82  319  63.8  34.0
26  洪柏宏  男   74  42   50  94  59  319  63.8  34.0
23  曾明軒  男   49  48   56  92  73  318  63.6  36.0
50  詹柏翰  男   42  44  100  74  57  317  63.4  37.0
43  吳雅萍  女   57  40   79  87  51  314  62.8  38.0
21  蘇彥宏  男   42  81   60  61  66  310  62.0  39.0
39  彭美慧  女   45  95   54  48  62  304  60.8  40.0
35  劉浩然  男   45  81   57  45  71  299  59.8  41.0
34  簡建宏  男   80  85   42  43  48  298  59.6  42.0
42  邱裕豪  男   54  75   52  49  67  297  59.4  43.0
3   吳子睿  男   42  65   49  65  76  297  59.4  43.0
4   蕭志明  男   64  50   45  71  63  293  58.6  45.0
11  葉柏翰  男   52  65   41  51  73  282  56.4  46.0
46  鍾浩銘  男   41  74   45  49  73  282  56.4  46.0
22  李柏融  男   42  84   55  51  49  281  56.2  48.0
48  劉婉婷  女   65  68   46  59  43  281  56.2  48.0
40  劉靜芬  女   62  51   71  41  41  266  53.2  50.0

In [11]:
from pandas import Series
def calulate(s:Series)-> int:
    n = (s < 60).sum()
    return n
    
scores_df['及格的科目數'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(calulate,axis=1)
scores_df

     姓名 性別   國文  英文   數學  地理  歷史   總分    平均    排名  及格的科目數
1   劉彥宏  男   98  87   50  40  58  333  66.6  26.0       3
2   曾彥廷  男   82  43   51  70  96  342  68.4  23.0       2
3   吳子睿  男   42  65   49  65  76  297  59.4  43.0       2
4   蕭志明  男   64  50   45  71  63  293  58.6  45.0       2
5   王文傑  男   81  63   98  89  89  420  84.0   1.0       0
6   朱冠霖  男   73  66   61  93  67  360  72.0  16.0       0
7   謝欣蓉  女   70  95   69  99  69  402  80.4   4.0       0
8   羅淑芬  女   90  67   55  53  58  323  64.6  33.0       3
9   許美慧  女   86  51   43  93  72  345  69.0  20.0       2
10  廖志豪  男   64  49   97  51  64  325  65.0  31.0       2
11  葉柏翰  男   52  65   41  51  73  282  56.4  46.0       3
12  呂承恩  男   93  88   42  52  69  344  68.8  21.0       2
13  蘇雅婷  女   42  95   40  86  61  324  64.8  32.0       2
14  高浩宇  男   90  87   95  47  84  403  80.6   2.0       1
15  王婉茹  女   79  51   91  66  90  377  75.4   8.0       1
16  莊承翰  男   84  78   44  69  51  326  65.2  29.0       2
17  黃裕傑  男   45  94   89  46  57  331  66.2  28.0       3
18  王冠廷  男  100  62   91  43  85  381  76.2   7.0       1
19  呂婉慧  女   83  79   46  62  92  362  72.4  15.0       1
20  莊子謙  男   86  48  100  64  74  372  74.4  11.0       1
21  蘇彥宏  男   42  81   60  61  66  310  62.0  39.0       1
22  李柏融  男   42  84   55  51  49  281  56.2  48.0       4
23  曾明軒  男   49  48   56  92  73  318  63.6  36.0       3
24  呂佳瑩  女   86  60   93  54  75  368  73.6  12.0       1
25  洪怡君  女   51  62   99  87  66  365  73.0  13.0       1
26  洪柏宏  男   74  42   50  94  59  319  63.8  34.0       3
27  江雅琪  女   69  84   89  91  59  392  78.4   5.0       1
28  郭怡萱  女   82  60   67  72  62  343  68.6  22.0       0
29  簡婉慧  女   78  67   75  65  41  326  65.2  29.0       1
30  楊靜宜  女   47  46   93  51  82  319  63.8  34.0       3
31  曾靜儀  女   60  95   80  82  59  376  75.2   9.0       1
32  蕭怡伶  女  100  94   72  80  46  392  78.4   5.0       1
33  洪裕豪  男   83  93   85  65  48  374  74.8  10.0       1
34  簡建宏  男   80  85   42  43  48  298  59.6  42.0       3
35  劉浩然  男   45  81   57  45  71  299  59.8  41.0       3
36  蕭浩宇  男   99  46   46  94  52  337  67.4  25.0       3
37  呂怡靜  女   68  48   71  90  71  348  69.6  18.0       1
38  邱宗翰  男   83  99   55  44  61  342  68.4  23.0       2
39  彭美慧  女   45  95   54  48  62  304  60.8  40.0       3
40  劉靜芬  女   62  51   71  41  41  266  53.2  50.0       3
41  許淑芬  女   93  59   98  58  44  352  70.4  17.0       3
42  邱裕豪  男   54  75   52  49  67  297  59.4  43.0       3
43  吳雅萍  女   57  40   79  87  51  314  62.8  38.0       3
44  施子軒  男   68  57   54  98  55  332  66.4  27.0       3
45  莊柏融  男   74  96   98  69  66  403  80.6   2.0       0
46  鍾浩銘  男   41  74   45  49  73  282  56.4  46.0       3
47  周美玲  女   89  40   95  66  74  364  72.8  14.0       1
48  劉婉婷  女   65  68   46  59  43  281  56.2  48.0       3
49  曾明哲  男   95  77   74  60  41  347  69.4  19.0       1
50  詹柏翰  男   42  44  100  74  57  317  63.4  37.0       3

In [18]:
def get_failing_subjects(row):
    subjects = ['國文', '英文', '數學', '地理', '歷史']
    failing = [subj for subj in subjects if row[subj] < 60]    
    return ','.join(failing) if failing else "無"
    
    
scores_df["不及格的科目名稱"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_failing_subjects,axis=1)
scores_df

     姓名 性別   國文  英文   數學  地理  歷史   總分    平均    排名  及格的科目數     不及格的科目名稱
1   劉彥宏  男   98  87   50  40  58  333  66.6  26.0       3     數學,地理,歷史
2   曾彥廷  男   82  43   51  70  96  342  68.4  23.0       2        英文,數學
3   吳子睿  男   42  65   49  65  76  297  59.4  43.0       2        國文,數學
4   蕭志明  男   64  50   45  71  63  293  58.6  45.0       2        英文,數學
5   王文傑  男   81  63   98  89  89  420  84.0   1.0       0            無
6   朱冠霖  男   73  66   61  93  67  360  72.0  16.0       0            無
7   謝欣蓉  女   70  95   69  99  69  402  80.4   4.0       0            無
8   羅淑芬  女   90  67   55  53  58  323  64.6  33.0       3     數學,地理,歷史
9   許美慧  女   86  51   43  93  72  345  69.0  20.0       2        英文,數學
10  廖志豪  男   64  49   97  51  64  325  65.0  31.0       2        英文,地理
11  葉柏翰  男   52  65   41  51  73  282  56.4  46.0       3     國文,數學,地理
12  呂承恩  男   93  88   42  52  69  344  68.8  21.0       2        數學,地理
13  蘇雅婷  女   42  95   40  86  61  324  64.8  32.0       2        國文,數學
14  高浩宇  男   90  87   95  47  84  403  80.6   2.0       1           地理
15  王婉茹  女   79  51   91  66  90  377  75.4   8.0       1           英文
16  莊承翰  男   84  78   44  69  51  326  65.2  29.0       2        數學,歷史
17  黃裕傑  男   45  94   89  46  57  331  66.2  28.0       3     國文,地理,歷史
18  王冠廷  男  100  62   91  43  85  381  76.2   7.0       1           地理
19  呂婉慧  女   83  79   46  62  92  362  72.4  15.0       1           數學
20  莊子謙  男   86  48  100  64  74  372  74.4  11.0       1           英文
21  蘇彥宏  男   42  81   60  61  66  310  62.0  39.0       1           國文
22  李柏融  男   42  84   55  51  49  281  56.2  48.0       4  國文,數學,地理,歷史
23  曾明軒  男   49  48   56  92  73  318  63.6  36.0       3     國文,英文,數學
24  呂佳瑩  女   86  60   93  54  75  368  73.6  12.0       1           地理
25  洪怡君  女   51  62   99  87  66  365  73.0  13.0       1           國文
26  洪柏宏  男   74  42   50  94  59  319  63.8  34.0       3     英文,數學,歷史
27  江雅琪  女   69  84   89  91  59  392  78.4   5.0       1           歷史
28  郭怡萱  女   82  60   67  72  62  343  68.6  22.0       0            無
29  簡婉慧  女   78  67   75  65  41  326  65.2  29.0       1           歷史
30  楊靜宜  女   47  46   93  51  82  319  63.8  34.0       3     國文,英文,地理
31  曾靜儀  女   60  95   80  82  59  376  75.2   9.0       1           歷史
32  蕭怡伶  女  100  94   72  80  46  392  78.4   5.0       1           歷史
33  洪裕豪  男   83  93   85  65  48  374  74.8  10.0       1           歷史
34  簡建宏  男   80  85   42  43  48  298  59.6  42.0       3     數學,地理,歷史
35  劉浩然  男   45  81   57  45  71  299  59.8  41.0       3     國文,數學,地理
36  蕭浩宇  男   99  46   46  94  52  337  67.4  25.0       3     英文,數學,歷史
37  呂怡靜  女   68  48   71  90  71  348  69.6  18.0       1           英文
38  邱宗翰  男   83  99   55  44  61  342  68.4  23.0       2        數學,地理
39  彭美慧  女   45  95   54  48  62  304  60.8  40.0       3     國文,數學,地理
40  劉靜芬  女   62  51   71  41  41  266  53.2  50.0       3     英文,地理,歷史
41  許淑芬  女   93  59   98  58  44  352  70.4  17.0       3     英文,地理,歷史
42  邱裕豪  男   54  75   52  49  67  297  59.4  43.0       3     國文,數學,地理
43  吳雅萍  女   57  40   79  87  51  314  62.8  38.0       3     國文,英文,歷史
44  施子軒  男   68  57   54  98  55  332  66.4  27.0       3     英文,數學,歷史
45  莊柏融  男   74  96   98  69  66  403  80.6   2.0       0            無
46  鍾浩銘  男   41  74   45  49  73  282  56.4  46.0       3     國文,數學,地理
47  周美玲  女   89  40   95  66  74  364  72.8  14.0       1           英文
48  劉婉婷  女   65  68   46  59  43  281  56.2  48.0       3     數學,地理,歷史
49  曾明哲  男   95  77   74  60  41  347  69.4  19.0       1           歷史
50  詹柏翰  男   42  44  100  74  57  317  63.4  37.0       3     國文,英文,歷史

In [17]:
[subj for subj in [30, 40, 50] if subj <= 40] #list綜合表達式
fallings = []
','.join(fallings) if fallings else "無"

'無'