In [26]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

#scores:ndarray | None = None # 學生的分數
#scores_df:DataFrame | None = None # 學生分數的DataFrame

scores:ndarray = np.random.randint(40, 101, size=(50, 5))
scores_df:DataFrame = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  63  43  72  50  87
7   謝欣蓉  女  90  91  90  50  94
8   羅淑芬  女  74  48  50  53  59
9   許美慧  女  42  77  75  62  98
10  廖志豪  男  54  49  46  71  98

In [33]:
scores_df[scores_df['姓名'] == '許美慧']
scores_df[scores_df['國文'] < 60]
scores_df.query("性別 == '女' and 國文 < 60 ")

     姓名 性別  國文  英文  數學  地理  歷史
9   許美慧  女  42  77  75  62  98
30  楊靜宜  女  45  95  84  47  46
32  蕭怡伶  女  55  41  64  47  69
39  彭美慧  女  57  63  95  57  41
41  許淑芬  女  44  79  84  45  60
43  吳雅萍  女  50  75  84  86  78
47  周美玲  女  54  46  80  63  94

In [49]:
scores_df["總分"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_df["平均"] = scores_df[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_df["排名"] = scores_df["總分"].rank(ascending=False,method='min')
scores_df.sort_values(by='排名')

     姓名 性別   國文  英文   數學   地理   歷史   總分    平均    排名
40  劉靜芬  女   88  94   96   75   76  429  85.8   1.0
31  曾靜儀  女   86  81   73   89   91  420  84.0   2.0
7   謝欣蓉  女   90  91   90   50   94  415  83.0   3.0
37  呂怡靜  女   90  57  100   90   76  413  82.6   4.0
42  邱裕豪  男  100  62   87   82   79  410  82.0   5.0
13  蘇雅婷  女   94  80   75   70   84  403  80.6   6.0
15  王婉茹  女   83  76   92   93   59  403  80.6   6.0
38  邱宗翰  男   55  91   99   90   63  398  79.6   8.0
48  劉婉婷  女   74  83   91   94   56  398  79.6   8.0
27  江雅琪  女   99  82   43   72  100  396  79.2  10.0
1   劉彥宏  男   63  90   72   91   76  392  78.4  11.0
21  蘇彥宏  男   93  68   96   75   58  390  78.0  12.0
12  呂承恩  男   76  94   53   76   83  382  76.4  13.0
36  蕭浩宇  男   75  86   84   53   77  375  75.0  14.0
43  吳雅萍  女   50  75   84   86   78  373  74.6  15.0
24  呂佳瑩  女   83  70   68   85   57  363  72.6  16.0
45  莊柏融  男   61  68   48   82   99  358  71.6  17.0
34  簡建宏  男   77  85   75   58   60  355  71.0  18.0
2   曾彥廷  男   72  68   90   50   74  354  70.8  19.0
11  葉柏翰  男   99  63   40   91   61  354  70.8  19.0
9   許美慧  女   42  77   75   62   98  354  70.8  19.0
28  郭怡萱  女   81  80   94   41   52  348  69.6  22.0
26  洪柏宏  男   60  70   91   74   53  348  69.6  22.0
46  鍾浩銘  男   88  83   67   56   52  346  69.2  24.0
16  莊承翰  男   95  60   64   54   67  340  68.0  25.0
18  王冠廷  男   48  40   88  100   63  339  67.8  26.0
47  周美玲  女   54  46   80   63   94  337  67.4  27.0
44  施子軒  男   79  46   43   88   72  328  65.6  28.0
5   王文傑  男   64  69   46   62   85  326  65.2  29.0
25  洪怡君  女   91  58   51   72   52  324  64.8  30.0
4   蕭志明  男   62  42   86   58   73  321  64.2  31.0
20  莊子謙  男   85  45   58   85   48  321  64.2  31.0
29  簡婉慧  女   77  48   53   58   84  320  64.0  33.0
10  廖志豪  男   54  49   46   71   98  318  63.6  34.0
30  楊靜宜  女   45  95   84   47   46  317  63.4  35.0
6   朱冠霖  男   63  43   72   50   87  315  63.0  36.0
39  彭美慧  女   57  63   95   57   41  313  62.6  37.0
41  許淑芬  女   44  79   84   45   60  312  62.4  38.0
23  曾明軒  男   99  40   48   45   78  310  62.0  39.0
19  呂婉慧  女   61  65   94   48   41  309  61.8  40.0
3   吳子睿  男   73  63   63   51   53  303  60.6  41.0
14  高浩宇  男   41  62   70   41   87  301  60.2  42.0
49  曾明哲  男   78  75   60   40   48  301  60.2  42.0
22  李柏融  男   56  56   51   63   75  301  60.2  42.0
50  詹柏翰  男   89  46   40   72   47  294  58.8  45.0
8   羅淑芬  女   74  48   50   53   59  284  56.8  46.0
17  黃裕傑  男   45  50   66   55   66  282  56.4  47.0
33  洪裕豪  男   46  70   66   45   54  281  56.2  48.0
32  蕭怡伶  女   55  41   64   47   69  276  55.2  49.0
35  劉浩然  男   56  54   50   63   51  274  54.8  50.0