In [1]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3]])
data

a  1   -1.108571
   2   -3.677450
   3   -0.050977
b  1    0.562698
   2   -0.763657
c  3    2.627235
   1   -0.397777
d  2    1.893875
   3   -0.332090
dtype: float64

In [5]:
data1 = data.unstack()
data1

          1         2         3
a -1.108571 -3.677450 -0.050977
b  0.562698 -0.763657       NaN
c -0.397777       NaN  2.627235
d       NaN  1.893875 -0.332090

In [6]:
data1.stack()

a  1   -1.108571
   2   -3.677450
   3   -0.050977
b  1    0.562698
   2   -0.763657
   3         NaN
c  1   -0.397777
   2         NaN
   3    2.627235
d  1         NaN
   2    1.893875
   3   -0.332090
dtype: float64

In [7]:
import numpy as np
import pandas as pd

frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                    index=[['a','a','b','b'],[1, 2, 1, 2]],
                    columns=[['台北','台北','台中'],['Green','Red','Green']])
frame.index.names = ['key1', 'key2']
frame.columns.names = ['縣市','顏色']
frame

縣市           台北        台中
顏色        Green Red Green
key1 key2
a    1        0   1     2
     2        3   4     5
b    1        6   7     8
     2        9  10    11

In [11]:
frame1 = frame.stack(['顏色','縣市'])
frame1

key1  key2  顏色     縣市
a     1     Green  台北     0
            Red    台北     1
            Green  台中     2
      2     Green  台北     3
            Red    台北     4
            Green  台中     5
b     1     Green  台北     6
            Red    台北     7
            Green  台中     8
      2     Green  台北     9
            Red    台北    10
            Green  台中    11
dtype: int64

In [12]:
frame1.unstack('key1')

key1           a   b
key2 顏色    縣市
1    Green 台中  2   8
           台北  0   6
     Red   台北  1   7
2    Green 台中  5  11
           台北  3   9
     Red   台北  4  10

In [13]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'key1':['a', 'a', 'b', 'b', 'a'],
                  'key2':['one', 'two', 'one', 'two', 'one'],
                  'data1': np.random.randn(5),
                  'data2':np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one -0.344760  0.589759
1    a  two -1.312265 -1.458096
2    b  one -0.332236  0.495940
3    b  two  1.663970 -0.143430
4    a  one  0.563118 -0.231710

In [17]:
df[['key1','data1','data2']].groupby('key1').sum()

         data1     data2
key1
a    -1.093907 -1.100047
b     1.331734  0.352511

In [18]:
df[['key1','data1','data2']].groupby('key1').mean()

         data1     data2
key1
a    -0.364636 -0.366682
b     0.665867  0.176255

In [23]:
df1 = df.groupby(['key1','key2']).sum()
df1.columns.name = "data"
df1

data          data1     data2
key1 key2
a    one   0.218359  0.358049
     two  -1.312265 -1.458096
b    one  -0.332236  0.495940
     two   1.663970 -0.143430

In [25]:
df1.stack().unstack(['key1','data'])

key1         a                   b
data     data1     data2     data1    data2
key2
one   0.218359  0.358049 -0.332236  0.49594
two  -1.312265 -1.458096  1.663970 -0.14343